AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: bracketologist stack

Resources:
  BracketologistProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BracketologistProcessor
      PackageType: Zip
      Runtime: python3.13
      CodeUri: service/lambdas/bracketAnalysis
      Handler: lambda_function.lambda_handler
      MemorySize: 1024
      Timeout: 90
      Environment:
        Variables:
          DB_READ: prod
          DB_WRITE: prod
          GROUP_TABLE: !Ref BracketologistGroups
          BRACKET_TABLE: !Ref BracketologistBrackets
      Layers:
        - arn:aws:lambda:us-east-2:336392948345:layer:AWSSDKPandas-Python313:1
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt BracketologistBrackets.Arn
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: !GetAtt BracketologistGroups.Arn

  BracketologistApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BracketologistApi
      PackageType: Zip
      Runtime: python3.13
      CodeUri: service/lambdas/bracketFetch
      Handler: lambda_function.lambda_handler
      MemorySize: 256
      Timeout: 5
      Environment:
        Variables:
          DB_READ: prod
          DB_WRITE: prod
          GROUP_TABLE: !Ref BracketologistGroups
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt BracketologistGroups.Arn
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /bracketologist/data/{groupId}
            Method: GET

  BracketologistKeyUpdate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BracketologistKeyUpdate
      PackageType: Zip
      Runtime: python3.13
      CodeUri: service/lambdas/bracketKeyUpdate
      Handler: lambda_function.lambda_handler
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          DB_READ: prod
          DB_WRITE: prod
          GROUP_TABLE: !Ref BracketologistGroups
          PROCESSOR_FUNCTION: !Ref BracketologistProcessor
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: !GetAtt BracketologistGroups.Arn
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt BracketologistProcessor.Arn
      Events:
        BracketologistKeySchedule:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)

  BracketologistGroups:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: BracketologistGroups
      PrimaryKey:
        Name: group_id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  BracketologistBrackets:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: BracketologistBrackets
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  BracketologistProcessorFunctionArn:
    Description: "ARN of the BracketologistProcessor function"
    Value: !GetAtt BracketologistProcessor.Arn
  BracketologistApiFunctionArn:
    Description: "ARN of the BracketologistApi function"
    Value: !GetAtt BracketologistApi.Arn
  BracketologistKeyUpdateFunctionArn:
    Description: "ARN of the BracketologistKeyUpdate function"
    Value: !GetAtt BracketologistKeyUpdate.Arn
  BracketologistGroupsTable:
    Description: "Bracketologist Groups Table"
    Value: !Ref BracketologistGroups
  BracketologistBracketsTable:
    Description: "Bracketologist Brackets Table"
    Value: !Ref BracketologistBrackets
  BracketologistApiUrl:
    Description: "Invoke URL for the API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bracketologist/data/{groupId}"
