CURRENT_YEAR = '2024'

mens_bracket = [
    {
        1:  'CONN',
        16: 'STET',
        8:  'FAU',
        9:  'NU',
        5:  'SDSU',
        12: 'UAB',
        4:  'AUB',
        13: 'YALE',
        6:  'BYU',
        11: 'DUQ',
        3:  'ILL',
        14: 'MORE',
        7:  'DRKE',
        10: 'WSU',
        2:  'ISU',
        15: 'SDST',
    },
    {
        1:  'UNC',
        16: 'WAG',
        8:  'MSST',
        9:  'MSU',
        5:  'SMC',
        12: 'GCU',
        4:  'ALA',
        13: 'COFC',
        6:  'CLEM',
        11: 'UNM',
        3:  'BAY',
        14: 'COLG',
        7:  'DAY',
        10: 'NEV',
        2:  'ARIZ',
        15: 'LBSU',
    },
    {
        1:  'HOU',
        16: 'LONG',
        8:  'NEB',
        9:  'TA&M',
        5:  'WIS',
        12: 'JMU',
        4:  'DUKE',
        13: 'UVM',
        6:  'TTU',
        11: 'NCSU',
        3:  'UK',
        14: 'OAK',
        7:  'FLA',
        10: 'COLO',
        2:  'MARQ',
        15: 'WKU',
    },
    {
        1:  'PUR',
        16: 'GRAM',
        8:  'USU',
        9:  'TCU',
        5:  'GONZ',
        12: 'MCN',
        4:  'KU',
        13: 'SAM',
        6:  'SC',
        11: 'ORE',
        3:  'CREI',
        14: 'AKR',
        7:  'TEX',
        10: 'CSU',
        2:  'TENN',
        15: 'SPU',
    }
]

mens_team_metadata = {
    'HOU': {'name': 'Houston',
            'abbrev': 'HOU',
            'seed': 1,
            'stat_seed': 0.5,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png'},
    'CONN': {'name': 'UConn',
             'abbrev': 'CONN',
             'seed': 1,
             'stat_seed': -0.75,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png'},
    'PUR': {'name': 'Purdue',
            'abbrev': 'PUR',
            'seed': 1,
            'stat_seed': 1.5,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png'},
    'UNC': {'name': 'North Carolina',
            'abbrev': 'UNC',
            'seed': 1,
            'stat_seed': 2.25,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png'},
    'ARIZ': {'name': 'Arizona',
             'abbrev': 'ARIZ',
             'seed': 2,
             'stat_seed': 1.75,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png'},
    'ISU': {'name': 'Iowa State',
            'abbrev': 'ISU',
            'seed': 2,
            'stat_seed': 2.0,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png'},
    'TENN': {'name': 'Tennessee',
             'abbrev': 'TENN',
             'seed': 2,
             'stat_seed': 2.5,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png'},
    'MARQ': {'name': 'Marquette',
             'abbrev': 'MARQ',
             'seed': 2,
             'stat_seed': 3.5,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/269.png'},
    'CREI': {'name': 'Creighton',
             'abbrev': 'CREI',
             'seed': 3,
             'stat_seed': 3.0,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/156.png'},
    'ILL': {'name': 'Illinois',
            'abbrev': 'ILL',
            'seed': 3,
            'stat_seed': 3.25,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png'},
    'BAY': {'name': 'Baylor',
            'abbrev': 'BAY',
            'seed': 3,
            'stat_seed': 4.0,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png'},
    'UK': {'name': 'Kentucky',
           'abbrev': 'UK',
           'seed': 3,
           'stat_seed': 4.5,
           'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png'},
    'AUB': {'name': 'Auburn',
            'abbrev': 'AUB',
            'seed': 4,
            'stat_seed': 2.75,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png'},
    'DUKE': {'name': 'Duke',
             'abbrev': 'DUKE',
             'seed': 4,
             'stat_seed': 3.75,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png'},
    'ALA': {'name': 'Alabama',
            'abbrev': 'ALA',
            'seed': 4,
            'stat_seed': 4.25,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png'},
    'KU': {'name': 'Kansas',
           'abbrev': 'KU',
           'seed': 4,
           'stat_seed': 5.0,
           'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png'},
    'SMC': {'name': "Saint Mary's",
            'abbrev': 'SMC',
            'seed': 5,
            'stat_seed': 5.5,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2608.png'},
    'GONZ': {'name': 'Gonzaga',
             'abbrev': 'GONZ',
             'seed': 5,
             'stat_seed': 4.75,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png'},
    'WIS': {'name': 'Wisconsin',
            'abbrev': 'WIS',
            'seed': 5,
            'stat_seed': 5.25,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png'},
    'SDSU': {'name': 'San Diego',
             'abbrev': 'SDSU',
             'seed': 5,
             'stat_seed': 6.0,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png'},
    'BYU': {'name': 'BYU',
            'abbrev': 'BYU',
            'seed': 6,
            'stat_seed': 5.75,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png'},
    'TTU': {'name': 'Texas Tech',
            'abbrev': 'TTU',
            'seed': 6,
            'stat_seed': 6.25,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png'},
    'CLEM': {'name': 'Clemson',
             'abbrev': 'CLEM',
             'seed': 6,
             'stat_seed': 7.25,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png'},
    'SC': {'name': 'South Carolina',
           'abbrev': 'SC',
           'seed': 6,
           'stat_seed': 9.25,
           'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png'},
    'TEX': {'name': 'Texas',
            'abbrev': 'TEX',
            'seed': 7,
            'stat_seed': 7.0,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png'},
    'FLA': {'name': 'Florida',
            'abbrev': 'FLA',
            'seed': 7,
            'stat_seed': 6.75,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png'},
    'DAY': {'name': 'Dayton',
            'abbrev': 'DAY',
            'seed': 7,
            'stat_seed': 8.25,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2168.png'},
    'WSU': {'name': 'Washington State',
            'abbrev': 'WSU',
            'seed': 7,
            'stat_seed': 9.0,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/265.png'},
    'MSST': {'name': 'Mississippi State',
             'abbrev': 'MSST',
             'seed': 8,
             'stat_seed': 7.5,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png'},
    'FAU': {'name': 'Florida Atlantic',
            'abbrev': 'FAU',
            'seed': 8,
            'stat_seed': 8.5,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png'},
    'NEB': {'name': 'Nebraska',
            'abbrev': 'NEB',
            'seed': 8,
            'stat_seed': 7.75,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png'},
    'USU': {'name': 'Utah State',
            'abbrev': 'USU',
            'seed': 8,
            'stat_seed': 11.0,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/328.png'},
    'MSU': {'name': 'Michigan State',
            'abbrev': 'MSU',
            'seed': 9,
            'stat_seed': 6.5,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png'},
    'TCU': {'name': 'TCU',
            'abbrev': 'TCU',
            'seed': 9,
            'stat_seed': 8.0,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png'},
    'TA&M': {'name': 'Texas A&M',
             'abbrev': 'TA&M',
             'seed': 9,
             'stat_seed': 9.5,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png'},
    'NU': {'name': 'Northwestern',
           'abbrev': 'NU',
           'seed': 9,
           'stat_seed': 10.25,
           'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png'},
    'COLO': {'name': 'Colorado',
             'abbrev': 'COLO',
             'seed': 10,
             'stat_seed': 9.75,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/38.png'},
    'DRKE': {'name': 'Drake',
             'abbrev': 'DRKE',
             'seed': 10,
             'stat_seed': 10.75,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2181.png'},
    'NEV': {'name': 'Nevada',
            'abbrev': 'NEV',
            'seed': 10,
            'stat_seed': 10.0,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png'},
    'CSU': {'name': 'Colorado State',
            'abbrev': 'CSU',
            'seed': 10,
            'stat_seed': 11.25,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/36.png'},
    'UNM': {'name': 'New Mexico',
            'abbrev': 'UNM',
            'seed': 11,
            'stat_seed': 8.75,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/167.png'},
    'NCSU': {'name': 'NC State',
             'abbrev': 'NCSU',
             'seed': 11,
             'stat_seed': 12.0,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png'},
    'ORE': {'name': 'Oregon',
            'abbrev': 'ORE',
            'seed': 11,
            'stat_seed': 11.5,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png'},
    'DUQ': {'name': 'Duquesne',
            'abbrev': 'DUQ',
            'seed': 11,
            'stat_seed': 13.0,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2184.png'},
    'JMU': {'name': 'James Madison',
            'abbrev': 'JMU',
            'seed': 12,
            'stat_seed': 12.25,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/256.png'},
    'MCN': {'name': 'McNeese',
            'abbrev': 'MCN',
            'seed': 12,
            'stat_seed': 12.5,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2377.png'},
    'GCU': {'name': 'Grand Canyon',
            'abbrev': 'GCU',
            'seed': 12,
            'stat_seed': 12.75,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2253.png'},
    'UAB': {'name': 'UAB',
            'abbrev': 'UAB',
            'seed': 12,
            'stat_seed': 13.75,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/5.png'},
    'YALE': {'name': 'Yale',
             'abbrev': 'YALE',
             'seed': 13,
             'stat_seed': 13.25,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/43.png'},
    'UVM': {'name': 'Vermont',
            'abbrev': 'UVM',
            'seed': 13,
            'stat_seed': 14.0,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/261.png'},
    'SAM': {'name': 'Samford',
            'abbrev': 'SAM',
            'seed': 13,
            'stat_seed': 13.5,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2535.png'},
    'COFC': {'name': 'Charleston',
             'abbrev': 'COFC',
             'seed': 13,
             'stat_seed': 14.25,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/232.png'},
    'MORE': {'name': 'Morehead State',
             'abbrev': 'MORE',
             'seed': 14,
             'stat_seed': 14.5,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2413.png'},
    'AKR': {'name': 'Akron',
            'abbrev': 'AKR',
            'seed': 14,
            'stat_seed': 14.75,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png'},
    'COLG': {'name': 'Colgate',
             'abbrev': 'COLG',
             'seed': 14,
             'stat_seed': 15.0,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2142.png'},
    'OAK': {'name': 'Oakland',
            'abbrev': 'OAK',
            'seed': 14,
            'stat_seed': 15.25,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2473.png'},
    'SDST': {'name': 'South Dakota',
             'abbrev': 'SDST',
             'seed': 15,
             'stat_seed': 15.75,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2571.png'},
    'WKU': {'name': 'Western Kentucky',
            'abbrev': 'WKU',
            'seed': 15,
            'stat_seed': 15.5,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/98.png'},
    'LBSU': {'name': 'Long Beach State',
             'abbrev': 'LBSU',
             'seed': 15,
             'stat_seed': 16.0,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/299.png'},
    'SPU': {'name': "Saint Peter's",
            'abbrev': 'SPU',
            'seed': 15,
            'stat_seed': 16.5,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2612.png'},
    'LONG': {'name': 'Longwood',
             'abbrev': 'LONG',
             'seed': 16,
             'stat_seed': 16.25,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2344.png'},
    'STET': {'name': 'Stetson',
             'abbrev': 'STET',
             'seed': 16,
             'stat_seed': 16.75,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/56.png'},
    'WAG': {'name': 'Wagner',
            'abbrev': 'WAG',
            'seed': 16,
            'stat_seed': 17.5,
            'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2681.png'},
    'GRAM': {'name': 'Grambling',
             'abbrev': 'GRAM',
             'seed': 16,
             'stat_seed': 17.75,
             'img': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2755.png'}}
